name: LaTeX-OCR-On-Action
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "准备模型文件"
        run: |
          cd model/checkpoints
          aria2c "https://github.com/lukas-blecher/LaTeX-OCR/releases/download/v0.0.1/image_resizer.pth"
          aria2c "https://github.com/lukas-blecher/LaTeX-OCR/releases/download/v0.0.1/weights.pth"
          cd ../..
      - name: "安装依赖"
        run: |
          pip install -U pix2tex[api] jinja2
      - name: "部署内网穿透服务"
        run: |
          aria2c "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
          sudo dpkg -i cloudflared-linux-amd64.deb
      - name: "启动服务"
        run: |
          nohup streamlit run api/streamlit.py & 
          cloudflared tunnel --url localhost:8501
      
